---
LOCATION: "kidderminster" #wx1
LOC2: "Bridgnorth" #wx2
LOC3: "worcester"#wx3
TIDE_LOCATION: "Swansea"
MYNODE: "862153020" #add node id number from liam cottles site 
MYNODES:
  - "3663493700"
  - "1234567890"
DBFILENAME: "./db/nodes2.db"
DM_MODE: True
FIREWALL: False
DUTYCYCLE: False #yes i turn it off while testing as it choked the bot too much
